[build]
# Pre-build: Install all dependencies and build shared packages
builder = "nixpacks"

[build.watchPatterns]
include = [
  "packages/**/*.ts",
  "apps/backend/**/*.ts", 
  "package.json",
  "packages/*/package.json",
  "apps/backend/package.json"
]

[deploy]
startCommand = "npm run start:railway"
restartPolicyType = "never"
restartPolicyMaxRetries = 10

[environments.production.variables]
NODE_ENV = "production"